### ISSUE TITLE
Add support for repository watching

### ISSUE THREAD

**Issue by ololduck** [paulollivier/fake-ci#10]
An easy thing to do would be to implement a scheduling mechanism to poll configured projects and build them on changes.

it would mean to be able to configure repository watching via a config file, for instance:

```toml
[[repos.fake-ci]]
url = "https://github.com/paulollivier/fake-ci"
poll = "*/5 * * * *"
branches = "*"
```

it would also mean to be able to run the executor in a binary, and *maybe* not launch any kind of webui.
